//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxy.DatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int DealId { get; set; }
        public string TraderId { get; set; }
        public int Quantity { get; set; }
        public double ExecPrice { get; set; }
        public string BookId { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public string Status { get; set; }
        public string InstrumentId { get; set; }
        public Nullable<double> ClearingFee { get; set; }
        public Nullable<double> TransactionFee { get; set; }
        public string Broker { get; set; }
        public string Counterparty { get; set; }
        public string Comment { get; set; }
    
        public virtual Instrument Instrument { get; set; }
        public virtual UserProfil UserProfil { get; set; }
    }
}
