//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxy.DatabaseService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevDbContext : DbContext
    {
        public DevDbContext()
            : base("name=DevDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HistoricalPrice> HistoricalPrice { get; set; }
        public virtual DbSet<Instrument> Instrument { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Deal> Deal { get; set; }
        public virtual DbSet<UserProfil> UserProfil { get; set; }
        public virtual DbSet<VolParam> VolParam { get; set; }
    }
}
