//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxy.DatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricalPrice
    {
        public string InstrumentId { get; set; }
        public double ClosePrice { get; set; }
        public System.DateTime AsOfDate { get; set; }
    
        public virtual Instrument Instrument { get; set; }
    }
}
