//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxy.DatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrument()
        {
            this.HistoricalPrices = new HashSet<HistoricalPrice>();
            this.Deals = new HashSet<Deal>();
        }
    
        public string Id { get; set; }
        public string ProductId { get; set; }
        public string FullName { get; set; }
        public string OptionType { get; set; }
        public Nullable<int> Strike { get; set; }
        public System.DateTime MaturityDate { get; set; }
        public string TtCode { get; set; }
        public string RefForwardId { get; set; }
        public string RefFutureId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricalPrice> HistoricalPrices { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deals { get; set; }
    }
}
