//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxy.DatabaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolParam
    {
        public string ProductId { get; set; }
        public System.DateTime MaturityDate { get; set; }
        public double A { get; set; }
        public double B { get; set; }
        public double Sigma { get; set; }
        public double Rho { get; set; }
        public double M { get; set; }
        public double Accuracy { get; set; }
        public double Guess { get; set; }
        public double LowerBound { get; set; }
        public double UpperBound { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
